### ISSUE TITLE
Update to the latest polkadot-js packages

### ISSUE THREAD

**Issue by alexsednz** [cennznet/api.js#129]
Polkadot API has experienced a major breaking change after the version 1.2.1 which has stopped our cennznet API to be able to update with the latest of this dependency. As the breaking change has happened a pretty long time ago and there have been several stable versions of Polkadot since that time, it is about time that we assessed how hard it is for us to adapt our own API to the latest.

**Comment by holygits** [comment]
Would close: #114

**Comment by holygits** [comment]
closed by #186
