### ISSUE TITLE
Type missed when calling api.query.genericAsset.locks function

### ISSUE THREAD

**Issue by AlexZhenWang** [cennznet/api.js#131]
Get type missed error when calling `api.query.genericAsset.locks` function
```
b = await api.query.genericAsset.locks('5FCdFHNPR62USs3xeA8Pnj2D87n4RLG1xRB2jS4tbcs7t19j')
Unable to decode storage genericAsset.locks: createType(Vec<BalanceLock>):: Unable to create Enum via index 31, in Fee, Misc, All
2020-07-27 18:46:50        RPC-CORE: subscribeStorage(keys: Vec<StorageKey>): StorageChangeSet:: createType(Vec<BalanceLock>):: Unable to create Enum via index 31, in Fee, Misc, All
```

**Comment by holygits** [comment]
`WithdrawReasons` is actually a bitmask and needs some special handling to decode properly.
This error will happen if the account has funds locked for `WithdrawReasons::all()` i.e. when staked.

Some solutions:
- Polkadot has some custom behaviour for it here, which we could look at pulling in:
https://raw.githubusercontent.com/polkadot-js/api/47fc4a2b3ce7ce1ed98e82bb61dbf2ff7c3cc904/packages/types/src/codec/Set.ts
- It might be simpler to treat `WithdrawReasons` as an integer and add the bit-masking checks manually for now

**Comment by AlexZhenWang** [comment]
Thank you, @holygits !
