### ISSUE TITLE
Can we get transactions history of an account? 

### ISSUE THREAD

**Issue by y4t0g4m1** [cennznet/api.js#168]
Currently, i follow the https://cennznet.io/ to integrate CENNZnet with our wallet, but i can't find the way the get the history of specific address.

**Comment by holygits** [comment]
Hi @y4t0g4m1 ,we don't provide that via cennznet.io at the moment. It would be coming as part of dedicated block scanner project, maybe @AlexZhenWang has some ideas

**Comment by AlexZhenWang** [comment]
Yeah, chain scanner has that feature, it’s currently under development and is coming soon

**Comment by y4t0g4m1** [comment]
Yeah, we are looking for that feature. Thank you guys, you just made my morning.
