### ISSUE TITLE
improve tx payment interface

### ISSUE THREAD

**Issue by holygits** [cennznet/api.js#244]
multi-currency fee payment API could provide a better interface to take % slip vs. guessing a large enough amount, quite clunky atm.

current API:
https://github.com/cennznet/api.js/blob/b803ce8169994751a43492a344fab2d1a7ddbbb4/packages/api/test/e2e/tx.e2e.ts#L160-L163

nicer API:
```ts
api.tx.genericAsset
  .transfer(spendingAssetId, bob.address, 100)
  .paymentOpts({ feeAssetId: CENNZ, slippage: 3 });
```

**Comment by KarishmaBothara** [comment]
@eupston -  check this commit - https://github.com/cennznet/api.js/commit/4dd7768b77ee6cfaf958122d604de6186b8ab8a4
It will give you idea of how to decorate the extrinsic to support paymentOpts... here you can see fee is decorated on extrinsic...            

            ```
const tx = api.tx.genericAsset.create({
                initialIssuance: 100,
            });
            const fee = await tx.fee(sender.address);
```

**Comment by eupston** [comment]
amazing thank you @KarishmaBothara. It looks like the custom cennznet extrinsics decorators were removed when updating to polkadot v1.1.1, although yeah this definitely gives me a good idea of how to reimplement.

**Comment by eupston** [comment]
@holygits just thinking about the design of this a bit more and currently we rely on creating the `transactionPayment` when going to `signAndSend`. So was your idea to wrap `signAndSend` in `paymentOpts`? Definitely doable but will require passing down a few extra params such as `assetOwner` and `tip`. 

Also would slippage percentage be based on the estimated fee of the provided `feeAssetId`?

**Comment by holygits** [comment]
So there's a couple ideas here.
Some might be infeasible and bigger than just this interface.

1) `api` could get the current price of the transaction in CPAY and user passes a slippage `%` on top, knowing the price estimate is accurate they just say they don't mind a maximum price shift of x%
internally I imagine this would query the current tx price and calculate current price * (1 +slippage/100)

To use this interface in it's current state the developer needs to query the price anyway so we could make it simpler for them by internalizing that...

2) It would be nice if the method chaining continued when setting other options
rather than passing to `signAndSend`

```js
api.tx.module.method
  .nonce(11)
  .paymentOpts({ assetId, slippage })
  .signAndSend(//...)
```
