### ISSUE TITLE
Don't break with new types

### ISSUE THREAD

**Issue by holygits** [cennznet/api.js#310]
When runtime gets a new module or types API refuses to connect because it's missing those types.
The recent 1.5.0/v40 release added new types in a backwards compatible way for the protocol (semver minor version bump)

this project should provide the same backward compatibility guarantee
e.g. it would be better if it failed to encode/decode new types rather than outright refuse to connect.

Overall this creates a bad experience for dapps which must update to handle it.

here's an example after recent 1.5.0/v40 upgrade

<img width="895" alt="Screen Shot 2021-05-25 at 15 31 32" src="https://user-images.githubusercontent.com/5133901/119435755-e7ec3000-bd6e-11eb-8c99-dd8f093cf9e8.png">

**Comment by holygits** [comment]
DApps could register for the endpoints they use e.g. `Api.connect(['system', 'cennzx', 'nft'])` might even help with the metadata decoding issue

**Comment by KarishmaBothara** [comment]
> DApps could register for the apis they use e.g. `Api.connect(['system', 'cennzx', 'nft'])` might even help with the metadata decoding issue

this is a good idea... if the list is empty, it will try to use the whole metadata for that genesisHash and specVersion... else use filtered metadata..
