### ISSUE TITLE
 METADATA: Unknown types found, no types for MetadataBaseURI

### ISSUE THREAD

**Issue by PathToLife** [cennznet/api.js#415]
Warning/Error like console log when starting up API on `2.1.0-alpha.0`

### Running
```typescript
import { Api } from '@cennznet/api';
const api = await Api.create({
  provider: 'wss://nikau.centrality.me/public/ws',
});
```

### Actual
`2022-02-10 13:58:03        METADATA: Unknown types found, no types for MetadataBaseURI`

### Expected
Clean start, no warning like / error like console logs.

### Env info
MacOS Monterey Latest as of 10 Feb 2022

`package.json` extract
```json
"dependencies": {
    "@cennznet/api": "^2.1.0-alpha.0",
    "@ethersproject/providers": "^5.4.5",
    "@polkadot/util": "^8.3.3",
    "ts-node": "^10.2.1",
    "typescript": "^4.5.5",
}
```

**Comment by KarishmaBothara** [comment]
thanks @PathToLife 
This is solved in  https://www.npmjs.com/package/@cennznet/api/v/2.1.0-alpha.1
