### ISSUE TITLE
Cannot start API on React-Native

### ISSUE THREAD

**Issue by developer-darpan** [cennznet/api.js#464]
Api initialization is failed with 
```
Super expression must either be null or a function
_wrapNativeSuper
    wrapNativeSuper.js:16:26
_wrapNativeSuper
    wrapNativeSuper.js:40:26
<unknown>
    UInt.js:1
loadModuleImplementation
    require.js:237:12
guardedLoadModule
    require.js:168:36
metroRequire
    require.js:152:20
<unknown>
    .....
```
on React-Native.

<img width="443" alt="Screen Shot 2022-04-26 at 2 55 47 PM (1)" src="https://user-images.githubusercontent.com/46893851/165398206-e705d743-9eb7-436a-a03e-a518b43025c4.png">

used dependencies:
```
    "@cennznet/api": "2.1.0-rc.2",
    "@cennznet/types": "2.1.0-rc.2",
    "react": "17.0.2",
    "react-native": "0.68.1"
```

Test repository to reproduce this issue: https://github.com/developer-darpan/cennznet-api-react-native

**Comment by ken-futureverse** [comment]
hey @developer-darpan great issue reporting :). Will take a look for you shortly.

**Comment by ken-futureverse** [comment]
@developer-darpan if you put in the following details in `metro.config.js`, it should fix the error as mentioned above, also it doesn't hurt to update `@cennznet/api` to use version `2.1.0`

```js
/**
 * Metro configuration for React Native
 * https://github.com/facebook/react-native
 *
 * @format
 */

const defaultSourceExts =
  require('metro-config/src/defaults/defaults').sourceExts;

const config = async () => {
  return {
    transformer: {
      getTransformOptions: async () => ({
        transform: {
          experimentalImportSupport: false,
          inlineRequires: true,
        },
      }),
    },
    resolver: {
      sourceExts: process.env.RN_SRC_EXT
        ? [
            ...process.env.RN_SRC_EXT.split(',').concat(defaultSourceExts),
            'cjs',
          ] // <-- cjs added here
        : [...defaultSourceExts, 'cjs'], // <-- cjs added here
    },
  };
};

module.exports = config();
```

```json
"@cennznet/api": "2.1.0",
"@cennznet/types": "2.1.0",
```

and depending on your project configuration, you might need to do [this](https://github.com/polkadot-js/common/issues/1321#issuecomment-1000194727) to bypass the error below 

![Screen Shot 2022-04-28 at 17 33 04](https://user-images.githubusercontent.com/97480229/165683635-1f1aea0b-3ce4-4b5e-bdb9-13cec9ee9452.png)

**Comment by developer-darpan** [comment]
> @developer-darpan if you put in the following details in `metro.config.js`, it should fix the error as mentioned above, also it doesn't hurt to update `@cennznet/api` to use version `2.1.0`
> 
> ```js
> /**
>  * Metro configuration for React Native
>  * https://github.com/facebook/react-native
>  *
>  * @format
>  */
> 
> const defaultSourceExts =
>   require('metro-config/src/defaults/defaults').sourceExts;
> 
> const config = async () => {
>   return {
>     transformer: {
>       getTransformOptions: async () => ({
>         transform: {
>           experimentalImportSupport: false,
>           inlineRequires: true,
>         },
>       }),
>     },
>     resolver: {
>       sourceExts: process.env.RN_SRC_EXT
>         ? [
>             ...process.env.RN_SRC_EXT.split(',').concat(defaultSourceExts),
>             'cjs',
>           ] // <-- cjs added here
>         : [...defaultSourceExts, 'cjs'], // <-- cjs added here
>     },
>   };
> };
> 
> module.exports = config();
> ```
> 
> ```json
> "@cennznet/api": "2.1.0",
> "@cennznet/types": "2.1.0",
> ```
> 
> and depending on your project configuration, you might need to do [this](https://github.com/polkadot-js/common/issues/1321#issuecomment-1000194727) to bypass the error below
> 
> ![Screen Shot 2022-04-28 at 17 33 04](https://user-images.githubusercontent.com/97480229/165683635-1f1aea0b-3ce4-4b5e-bdb9-13cec9ee9452.png)

Thanks, @ken-centrality 😊

**Comment by ken-futureverse** [comment]
all good @developer-darpan, please close the this if it solves your issue.

**Comment by ken-futureverse** [comment]
gonna close this now @developer-darpan, re-open it if it doesn't solve your issue
